name: Create develop Pull Request

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create_develop_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create new Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: "Update develop branch with changes from ${{github.event.pull_request.head.ref}}"
        branch: ${{github.event.pull_request.head.ref}}
        title: "Update develop branch with changes from ${{github.event.pull_request.head.ref}}"
        body: |
          This pull request updates the develop branch with changes from the ${{github.event.pull_request.head.ref}} branch.

        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        base: develop
